version: "3"

services:
  port-forwarding:
    build:
      context: ./port-forwarding
      dockerfile: Dockerfile
    image: ahkui/port-forwarding:latest

  wrk:
    build:
      context: ./wrk
      dockerfile: Dockerfile
    image: ahkui/wrk:latest

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: ahkui/jupyter:latest

  jupyterhub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile
    image: ahkui/jupyterhub:latest

  jupyter-cpu:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
        JUPYTERHUB_ENABLE_NVIDIA: "false"
    image: ahkui/jupyter:cpu

  jupyter-ml-cpu:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
        JUPYTERHUB_ENABLE_NVIDIA: "false"
    image: ahkui/jupyter:ml-cpu

  jupyter-ml:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
    image: ahkui/jupyter:ml

  jupyter-gpu:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
    image: ahkui/jupyter:gpu

  jupyter-ml-gpu:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
    image: ahkui/jupyter:ml-gpu
