version: "3"

services:
  wrk:
    build:
      context: ./wrk
      dockerfile: Dockerfile
    image: ahkui/wrk:latest

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: ahkui/jupyter:latest

  jupyterhub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile
    image: ahkui/jupyterhub:latest

  jupyter-ml:
    build:
      context: ./jupyter
      dockerfile: ml.Dockerfile
      args:
        OPENPOSE_MODELS_PROVIDER: https://openpose.ahkui.com/
    image: ahkui/jupyter:ml

  jupyter-ml-cpu:
    build:
      context: ./jupyter
      dockerfile: ml-cpu.Dockerfile
    image: ahkui/jupyter:ml-cpu

  jupyter-ml-gpu:
    build:
      context: ./jupyter
      dockerfile: ml-gpu.Dockerfile
    image: ahkui/jupyter:ml-gpu
